name: Publish Python Package to PyPI

on:
  release:
    types: [released, prereleased]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Hatch
        run: pip install hatch

      - name: Verify tag matches version
        run: |
          VERSION_IN_FILE=$(hatch version)
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "Tag: $TAG_NAME | Version: $VERSION_IN_FILE"
          if [ "$VERSION_IN_FILE" != "$TAG_NAME" ]; then
            echo "[X] Tag ($TAG_NAME) does not match version in pyproject.toml ($VERSION_IN_FILE)"
            exit 1
          fi

      - name: Build the package
        run: hatch build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/nepali_calendar_utils/${{ github.ref_name }}

    permissions:
      id-token: write

    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/